name: Docker

on:
  schedule:
    # every day at 00:15 UTC
    # https://crontab.guru/#15_0_*_*_*
    - cron: '15 0 * * *'
  push:
    branches:
      - 'main'
    # Publish calver or pep440 tags as releases.
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
  pull_request:
    branches:
      - 'main'

jobs:
  setup:
    name: Setup

    # Build all multi-platform Docker images, all stages. The specified
    # stages (in ./.github/stages.json) are built one after the other
    # for the specified platforms (in ./.github/platforms.json) and,
    # if successful, are finally merged via a Docker manifest and
    # published to the Docker registry on GitHub.
    uses: tiacsys/github-workflows/.github/workflows/docker-stages.yml@v1
    with:
      ghr-free-disk: false
      platforms-json: ./.github/platforms.json
      stages-json: ./.github/stages.json
    secrets: inherit # pass all secrets
